name: Deploy inteliagro-app to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [aws-ec2]  # Rodar diretamente no runner EC2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build Docker image on EC2
        run: docker build -t inteliagro-app .

      - name: Stop and remove old containers
        run: docker-compose down || true  # Parar apenas o serviço da aplicação
      
      - name: Start new containers
        run: docker-compose up --build -d
