name: deploy inteliagro

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login on my docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build docker image
        run: docker build -t jamillalobo/inteliagro-app .
      - name: Push docker image on docker hub
        run: docker push jamillalobo/inteliagro-app:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Stop and remove old containers
        run: docker-compose down

      - name: Pull latest Docker image
        run: docker pull jamillalobo/inteliagro-app:latest 

      - name: Build and start containers
        run: docker-compose up --build -d 