name: deploy inteliagro

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Login on my docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t jamillalobo/inteliagro-app . 
      - name: Push docker image on docker hub
        run: docker push jamillalobo/inteliagro-app:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Stop and remove old containers
        run: |
          cd actions-runner  # Ensure you are in the correct directory
          docker-compose down
      - name: Build and start containers
        run: |
          cd actions-runner  # Ensure you are in the correct directory
          docker-compose up --build -d
