name: deploy inteliagro

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build docker image for app
        run: docker build -t inteliagro-app .

      - name: Build docker image for db
        run: docker build -t inteliagro-db .

      - name: Save docker images
        run: |
          docker save inteliagro-app -o inteliagro-app.tar
          docker save inteliagro-db -o inteliagro-db.tar

      - name: Upload images as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: docker-images
          path: |
            inteliagro-app.tar
            inteliagro-db.tar

  deploy:
    # O runner é self-hosted, então ele pode acessar diretamente os arquivos da própria máquina
    needs: build
    runs-on: [self-hosted, linux]
    steps:
      - name: Download docker images
        run: |
          # Como o runner está rodando localmente na mesma máquina, você não precisa baixar os arquivos.
          # Se os arquivos foram criados na mesma máquina, apenas use-os diretamente.

          # Carregar as imagens Docker criadas
          docker load -i inteliagro-app.tar
          docker load -i inteliagro-db.tar

      - name: Stop and remove old containers
        run: docker-compose down

      - name: Build and start containers
        run: docker-compose up --build -d
