name: deploy inteliagro

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build docker image for app
        run: docker build -t inteliagro-app .

      - name: Save docker image for app
        run: docker save inteliagro-app -o inteliagro-app.tar

      - name: Upload app image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image-app
          path: inteliagro-app.tar

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Clean up Docker
        run: |
          docker container prune -f
          docker image prune -a -f
          docker volume prune -f

      - name: Download app image
        uses: actions/download-artifact@v3
        with:
          name: docker-image-app

      - name: Load docker image
        run: docker load -i inteliagro-app.tar

      - name: Stop and remove old containers
        run: docker-compose down

      - name: Pull latest postgres image
        run: docker pull postgres:latest

      - name: Build and start containers
        run: docker-compose up --build -d
